name: cat_tinder_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  cached_network_image: ^3.4.1
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  connectivity_plus: ^4.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/like_dark.png
    - assets/images/dislike_dark.png
    - assets/images/like_light.png
    - assets/images/dislike_light.png
    - assets/images/loading_cat.png
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
